name: Generate Quantum Wave Animation

on:
  # Run every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate contribution animation
    steps:
      # Check out repository
      - uses: actions/checkout@v2
      
      # Generate the snake animation
      - name: Generate Quantum Wave Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # Generate the standard snake SVG file
          svg_out_path: dist/github-contribution-grid-quantum-wave.svg
          
      # Push the generated files to the output branch
      - name: Push files to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
